when:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  prepare:
    image: alpine
    commands:
      - mkdir -p build/slides
      - apk add --no-cache rsync
      - >
        rsync -av -r
        --include='*/'
        --include='*.jpg'
        --include='*.png'
        --include='*.svg'
        --include='*.gif'
        --include='*.mp4'
        --include='*.webp'
        --exclude='*'
        slides/ build/slides/

  marp_html:
    image: marpteam/marp-cli:v4.1.1
    environment:
      MARP_USER: root:root
      PUPPETEER_TIMEOUT: "0"
    commands:
      - docker-entrypoint -c package.json --allow-local-files

  marp_pdf:
    image: marpteam/marp-cli:v4.1.1
    environment:
      MARP_USER: root:root
      PUPPETEER_TIMEOUT: "0"
    commands:
      - docker-entrypoint -c package.json --pdf --allow-local-files --pdf-notes=false

  deploy_pages:
    image: alpine/git
    environment:
      CODEBERG_TOKEN:
        from_secret: woodpecker_token
    commands:
      - git config --global user.name "woodpecker"
      - git config --global user.email "ci@codeberg.org"

      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git deploy_dir || (mkdir deploy_dir && cd deploy_dir && git init && git checkout -b pages && cd ..)

      - rm -rf deploy_dir/*
      - cp -r build/slides/* deploy_dir/

      - cd deploy_dir
      - git add .
      - |
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Deploy slides: ${CI_COMMIT_SHA:0:7}"
          git push https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git pages
        else
          echo "No changes to deploy."
        fi
