name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images
        run: rsync -r --include='*/' --include='*.jpg' --include='*.png' --include='*.svg' --include='*.gif' --include='*.mp4' --exclude='*' slides/ build/slides/

      - name: Marp Build
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: -c package.json --allow-local-files
        env:
          MARP_USER: root:root

      - name: Marp Build to pdf
        uses: docker://marpteam/marp-cli:v3.4.0
        with:
          args: -c package.json --pdf --allow-local-files
        env:
          MARP_USER: root:root
          
      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/slides/
          clean-exclude: pr-preview/

